import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Editor.module.css'
import Header from '../components/Header'
import Footer from '../components/Footer'
import VariantMenu from '../components/VariantMenu'
import TraitMenu from '../components/TraitMenu'
import ToolBar from '../components/ToolBar'
import FileDropModal from '../components/FileDropModal'

import { useState, useEffect } from 'react'

// UTILs
import selectTrait from '../utils/selectTrait'


export default function Editor() {
  let [res, setRes] = useState([])
  useEffect(() => {
    let test = [
      ["red", 0],
      ["green", 0],
      ["yellow", 7],
      ["blue", 0],
    ]
    // let result
      setRes([selectTrait(test), selectTrait(test), selectTrait(test), selectTrait(test)])
  }, [])
  
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header/>
        {/* <header className="bg-white shadow">
          <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
            <h1 className="text-3xl font-bold text-gray-900">Dashboard</h1>
          </div>
        </header> */}
      <main className={styles.main}>


      <p>{res.map(i => i + ", " )}</p>
        
 

      <div className={styles.leftPanel}>
        <TraitMenu/>
        <VariantMenu/>
      </div>
      <div className={styles.mainPanel}>
      <div className={styles.screen}>
        
        </div>
        <div className={styles.variantInfo}>

        </div>
      </div>
      <div className={styles.rightPanel}>
        <ToolBar/>
        
      </div>
      </main>
        <Footer/>
        {/* <FileDropModal/> */}
    </div>
  )
}
